# Generated by Django 6.1.1 on 2026-09-22 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_allergen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='serving_unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_basis_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_basis_unit',
            field=models.CharField(choices=[('G', 'Gram'), ('ML', 'Milliliter')], default='G', max_length=5),
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='nutrition.allergen')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='nutrition.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'allergen'), name='unique_ingredient_allergen')],
            },
        ),
    ]
