# Generated by Django 6.1.1 on 2026-09-24 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MORNING_SNACK', 'Morning Snack'), ('LUNCH', 'Lunch'), ('EVENING_SNACK', 'Evening Snack'), ('DINNER', 'Dinner')], max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('prep_time', models.PositiveIntegerField(help_text='Preparation time in minutes.')),
                ('cook_time', models.PositiveIntegerField(help_text='Cooking time in minutes.')),
                ('servings', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
