# Generated by Django 6.1.1 on 2026-09-24 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('nutrition', '0007_remove_ingredient_serving_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('G', 'Gram'), ('ML', 'Milliliter')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_ingredients', to='nutrition.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='meals.meal')),
            ],
        ),
    ]
