# Generated by Django 6.1.1 on 2026-09-24 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_tag_mealtag'),
        ('nutrition', '0007_remove_ingredient_serving_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDietaryPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dietary_preference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meals', to='nutrition.dietarypreference')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to='meals.meal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meal', 'dietary_preference'), name='unique_meal_dietary_preference')],
            },
        ),
    ]
