# Generated by Django 6.1.1 on 2026-09-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_unit', models.CharField(default='CM', max_length=5)),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_unit', models.CharField(default='KG', max_length=5)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary'), ('LIGHTLY_ACTIVE', 'Lightly Active'), ('MODERATELY_ACTIVE', 'Moderately Active'), ('VERY_ACTIVE', 'Very Active')], max_length=30)),
                ('goal', models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MAINTENANCE', 'Weight Maintenance'), ('WEIGHT_GAIN', 'Weight Gain'), ('MUSCLE_BUILDING', 'Muscle Building')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
