# Generated by Django 6.1.1 on 2026-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='height_unit',
            field=models.CharField(choices=[('CM', 'Centimeters'), ('FT', 'Feet')], default='CM', max_length=5),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight_unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds')], default='KG', max_length=5),
        ),
    ]
